version: "3.8"

services:
    ai_model:
        container_name: ai_model
        env_file:
            - ./.env
        build:
            context: ./ai_model_for_mobile
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  capabilities: [ gpu ]
        ports:
            - 8001:80
        restart: always
    backend:
        container_name: backend
        env_file:
            -   ./.env
        command: sh -c "gunicorn django_core.wsgi:application --bind 0.0.0.0:80 --reload"
        build:
            context: ./django_core
        ports:
            -   8002:80
        volumes:
            - ./django_core:/app
        restart: always
