# Generated by Django 4.2.7 on 2023-11-08 11:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesthistory",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default="", upload_to="images"
            ),
            preserve_default=False,
        ),
    ]
