# Generated by Django 4.2.7 on 2023-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_service", "0002_requesthistory_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestHistory",
        ),
    ]
