# Generated by Django 4.2.7 on 2023-11-08 13:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(upload_to="images"),
                ),
            ],
        ),
    ]
