# Generated by Django 4.2.7 on 2023-11-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_requests", "0002_requesthistory_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requesthistory",
            old_name="description",
            new_name="ai_description",
        ),
        migrations.AddField(
            model_name="requesthistory",
            name="user_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
